
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
addons:
  apt:
    packages:
      - librdf0-dev
      - libv8-dev
after_success:
  - Rscript -e 'covr::codecov()'

## alternately test via docker
#sudo: required
#services:
#  - docker
#script:
#  - ./test.sh


